var TourConstants = {
  DASHBOARD: "DASHBOARD",
  DECK_INDEX: "DECK_INDEX",
  DECK_SHOW: "DECK_SHOW",
  REVIEW_FRONT: "REVIEW_FRONT",
  REVIEW_FLIPPED: "REVIEW_FLIPPED",
  REVIEW_RECAP: "REVIEW_RECAP",
  DECK_IMPORT: "DECK_IMPORT"
}

module.exports = TourConstants;
